/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_act365_sudoku_Solver */

#ifndef _Included_com_act365_sudoku_Solver
#define _Included_com_act365_sudoku_Solver
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
#undef com_act365_sudoku_Solver_MIN_PRIORITY
#define com_act365_sudoku_Solver_MIN_PRIORITY 1L
#undef com_act365_sudoku_Solver_NORM_PRIORITY
#define com_act365_sudoku_Solver_NORM_PRIORITY 5L
#undef com_act365_sudoku_Solver_MAX_PRIORITY
#define com_act365_sudoku_Solver_MAX_PRIORITY 10L
/*
 * Class:     com_act365_sudoku_Solver
 * Method:    _solve
 * Signature: (Lcom/act365/sudoku/LeastCandidatesHybrid;Lcom/act365/sudoku/MostCandidates;IIZII)I
 */
JNIEXPORT jint JNICALL Java_com_act365_sudoku_Solver__1solve
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
